
FROM node:lts AS builder


WORKDIR /backend/src

COPY ./backend/src/package*.json ./


RUN npm install

COPY ../../backend/src/ ./

RUN npm run build

RUN groupadd -r appgroup && useradd -r -g appgroup -s /bin/false appuser
RUN chown -R appuser:appgroup /usr/src/app


FROM node:slim

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/package*.json ./

# Copier les informations de l'utilisateur
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group

# Définir l'utilisateur
USER appuser

EXPOSE 5000


CMD ["node", "dist/app.js"]